code-style
rkhozinov/jenkins-jobs pull request #11
Opened 2016-11-25 15:37 UTC by naumvd95

2016-11-25 15:40 UTC, rkhozinov requested changes

2016-11-25 15:40 UTC, rkhozinov commented on servers/partner-ci/9.x/nsxv.yaml
> +          PLUGIN_VERSION=3.0.0
3.0.1 ?

2016-11-25 15:41 UTC, rkhozinov requested changes

2016-11-25 15:41 UTC, rkhozinov commented on servers/partner-ci/9.x/nsxv.yaml
> +          PLUGIN_VERSION=3.0.0
https://review.openstack.org/#/c/401266/2/plugin_test/tests/test_plugin_nsxv.py

2016-11-28 09:11 UTC, rkhozinov commented
need to rebase it, because master was rebased

2016-11-28 09:12 UTC, naumvd95 commented
please clarify, how can i help u

2016-11-28 10:54 UTC, closed without merging