fix reverting to avoid nfs issue
rkhozinov/jenkins-jobs pull request #110
Opened 2017-01-10 09:55 UTC by naumvd95

watch the state
http://jenkins-tpi.bud.mirantis.net:8080/job/9.x.vcenter.vcenter_dvs_bvt/123/console

2017-01-10 09:58 UTC, rkhozinov requested changes

2017-01-10 09:58 UTC, rkhozinov commented on servers/partner-ci/builders/workstation.sh
> +    echo "restart services to avoid connection problems>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
remove >>>

2017-01-10 09:58 UTC, rkhozinov commented on servers/partner-ci/builders/workstation.sh
> +   ####uncomment below rows if you want to check esxi-information
remove commented lines

2017-01-10 10:20 UTC, rkhozinov requested changes
- Running ESXShell restart
- Running SSH restart
- Running nscd restart
- Running ntpd restart
- SSH login enabled
- Starting ntpd

2017-01-10 11:50 UTC, naumvd95 commented on servers/partner-ci/builders/workstation.sh
> +   ####uncomment below rows if you want to check esxi-information
need to wrap it by checker DEBUG

2017-01-12 10:37 UTC, rkhozinov requested changes

2017-01-12 10:37 UTC, rkhozinov commented on servers/partner-ci/builders/workstation.sh
> +      python2 $SSH_ENDPOINT $esxi_host $ESXI_USER $ESXI_PASSWORD 'esxcli system syslog config get'
refactor to function

remote_exec (){
host=$1
command=$2
 python2 $SSH_ENDPOINT $host $ESXI_USER $ESXI_PASSWORD $cmd
 echo "$cmd-------------------------------------------------------"
}

2017-01-12 13:47 UTC, rkhozinov requested changes

2017-01-12 13:47 UTC, rkhozinov commented on servers/partner-ci/builders/workstation.sh
> -  source $VENV_PATH/bin/activate
revert that

2017-01-12 13:48 UTC, rkhozinov requested changes

2017-01-12 13:48 UTC, rkhozinov commented on servers/partner-ci/builders/workstation.sh
> +      if esxi_exec $esxi_host "esxcli storage nfs add -H $NFS_SERVER -s /var/$nfs_share -v $nfs_share"; then
- do nfs_share addition on esxi host `esxi_exec "for nfs_share in $NFS_SHARES"`...
- create a variable with list of commands and then execute them in cycle
- may be you need to reassign an error-code from paramiko 
- after 'esxcli storage core adapter rescan --all' need to check, that nfs are connected and active 
OR 
you can use a simple ansible-playbook to do all that stuff

2017-01-12 14:55 UTC, rkhozinov approved these changes

2017-01-17 10:31 UTC, naumvd95 commented on servers/partner-ci/builders/workstation.sh
> +      if esxi_exec $esxi_host "esxcli storage nfs add -H $NFS_SERVER -s /var/$nfs_share -v $nfs_share"; then
1,2 = seems seems there is no normal code-style cases
3,4=done
3- test http://jenkins-tpi.bud.mirantis.net:8080/job/9.x.vcenter.custom.qa/65/console

2017-01-17 12:53 UTC, merged