fix #124
rkhozinov/jenkins-jobs pull request #126
Opened 2017-01-17 13:57 UTC by naumvd95

2017-01-17 15:43 UTC, rkhozinov requested changes

2017-01-17 15:43 UTC, rkhozinov commented on .travis.yml
> +  - bash -c 'grep -R -E "[^$]{[a-zA-Z0-9_-]+}" output; if [ $? == 0 ]; then exit 1; fi'
- bash -c 'grep -R -E "[^$]{[a-zA-Z0-9_-]+}" output/ && exit 1'

2017-01-18 06:53 UTC, naumvd95 commented
The command "bash -c 'grep -R -E "[^$]{[a-zA-Z0-9_-]+}" ./output && exit 1'" exited with 1.
https://travis-ci.org/rkhozinov/jenkins-jobs/builds/192947101
unfortunately your case failed checks

2017-01-18 09:59 UTC, rkhozinov approved these changes

2017-01-18 09:59 UTC, merged