direct wiping all jenkins-workspace before build
rkhozinov/jenkins-jobs pull request #146
Opened 2017-01-26 14:49 UTC by naumvd95

2017-01-26 15:07 UTC, rkhozinov requested changes

2017-01-26 15:07 UTC, rkhozinov commented on servers/partner-ci/common.yaml
> +      - workspace-cleanup
rename to **artifacts-cleanup**

2017-01-26 15:07 UTC, rkhozinov commented on servers/partner-ci/builders/vcenter.test.sh
> +[ -f nosetests.xml ] && sudo rm -f nosetests.xml
remove that - because we have **artifacts cleanup**

2017-01-26 15:07 UTC, rkhozinov commented on servers/partner-ci/builders/ui.test.sh
> +[ -f nosetests.xml ] && sudo rm -f nosetests.xml
remove that - because we have **artifacts cleanup**

2017-01-26 15:07 UTC, rkhozinov commented on servers/partner-ci/builders/dvs.test.sh
> +[ -f nosetests.xml ] && sudo rm -f nosetests.xml
remove that - because we have **artifacts cleanup**

2017-01-26 15:07 UTC, rkhozinov commented on servers/partner-ci/builders/contrail.test.sh
> +[ -f nosetests.xml ] && sudo rm -f nosetests.xml
remove that - because we have **artifacts cleanup**

2017-01-26 15:54 UTC, naumvd95 commented on servers/partner-ci/builders/vcenter.test.sh
> +[ -f nosetests.xml ] && sudo rm -f nosetests.xml
done

2017-01-26 15:54 UTC, naumvd95 commented on servers/partner-ci/builders/ui.test.sh
> +[ -f nosetests.xml ] && sudo rm -f nosetests.xml
done

2017-01-26 15:55 UTC, naumvd95 commented on servers/partner-ci/builders/dvs.test.sh
> +[ -f nosetests.xml ] && sudo rm -f nosetests.xml
doen

2017-01-26 15:55 UTC, naumvd95 commented on servers/partner-ci/builders/contrail.test.sh
> +[ -f nosetests.xml ] && sudo rm -f nosetests.xml
done

2017-01-27 07:15 UTC, naumvd95 commented on servers/partner-ci/common.yaml
> +      - workspace-cleanup
i cant rename it
this is default name of plugin-jjb configuration

2017-01-27 10:51 UTC, rkhozinov commented on servers/partner-ci/common.yaml
> +      - workspace-cleanup
ok

2017-01-27 11:07 UTC, rkhozinov requested changes
Don't need wipe all data in workspace.
We don't need only log and xml artifacts

2017-01-30 07:35 UTC, naumvd95 commented
@rkhozinov re-review please

2017-01-30 07:53 UTC, rkhozinov approved these changes

2017-01-30 07:53 UTC, merged