rescan_datastores: refactoring
rkhozinov/jenkins-jobs pull request #150
Opened 2017-01-31 11:48 UTC by rkhozinov

2017-01-31 12:42 UTC, ekhomyakova requested changes
I don't like it

2017-01-31 12:56 UTC, ekhomyakova requested changes

2017-01-31 12:56 UTC, ekhomyakova commented on servers/partner-ci/builders/rescan_ds.py
> +        self.datacenter = dc_name
What is the difference between `self.dc_name` and `self.datacenter`?

2017-01-31 13:13 UTC, ekhomyakova requested changes

2017-01-31 13:13 UTC, ekhomyakova commented on servers/partner-ci/builders/rescan_ds.py
> +        [host.configManager.storageSystem.RescanAllHba() for host in self.hosts]
Don't create new object. There is nothing bad in usual loop.

2017-01-31 13:13 UTC, ekhomyakova commented on servers/partner-ci/builders/rescan_ds.py
> +            self._hosts = [host for host in host_view.view ]
Redundant space

2017-01-31 13:13 UTC, ekhomyakova commented on servers/partner-ci/builders/rescan_ds.py
> +
Remove the line

2017-01-31 13:16 UTC, ekhomyakova requested changes

2017-01-31 13:16 UTC, ekhomyakova commented on servers/partner-ci/builders/rescan_ds.py
> +            host_view = self.content.viewManager.CreateContainerView(self.datacenter,
Move `self.datacenter,` to the new line.

2017-01-31 13:16 UTC, ekhomyakova commented on servers/partner-ci/builders/rescan_ds.py
Remove the line

2017-01-31 13:16 UTC, ekhomyakova commented on servers/partner-ci/builders/rescan_ds.py
> +                    password=password, port=port)
Edit formatting

2017-01-31 13:16 UTC, ekhomyakova commented on servers/partner-ci/builders/rescan_ds.py
> +                    password=password, port=port)
Add empty line after last one.

2017-01-31 14:28 UTC, rkhozinov commented
recheck

2017-01-31 15:16 UTC, rkhozinov commented on servers/partner-ci/builders/rescan_ds.py
done

2017-01-31 15:52 UTC, rkhozinov commented on servers/partner-ci/builders/rescan_ds.py
> +execfile(jenkins_venv, dict(__file__=jenkins_venv))
awesome

2017-01-31 15:53 UTC, rkhozinov commented on .travis.yml
> +  - bash -c 'grep --color -R -E "[^$]{[a-zA-Z0-9_-]+}" ./output && exit 1 || echo "there is no undefined variables"'
not good 
that merge has broken travis

2017-01-31 15:58 UTC, rkhozinov commented on servers/partner-ci/builders/rescan_ds.py
> +jenkins_venv = "/home/jenkins/90-venv/bin/activate_this.py"
@naumvd95 remove hardcode for virtual_env
use VIRTUAL_ENV variable instead

2017-01-31 16:00 UTC, ekhomyakova requested changes

2017-01-31 16:00 UTC, ekhomyakova commented on .travis.yml
> +      - debian-sid    # Grab shellcheck from the Debian repo (o_O)
Remove " (o_O)"

2017-01-31 16:00 UTC, ekhomyakova commented on servers/partner-ci/builders/rescan_ds.py
> +
Is it needed?

2017-01-31 16:00 UTC, ekhomyakova commented on servers/partner-ci/builders/rescan_ds.py
> +jenkins_venv = "/home/jenkins/90-venv/bin/activate_this.py"
Don't hardcode path

2017-01-31 16:00 UTC, ekhomyakova commented on servers/partner-ci/builders/rescan_ds.py
> +            host_view = self.content.viewManager.CreateContainerView(self.datacenter,
Move `self.datacenter,` to the next line

2017-01-31 16:00 UTC, ekhomyakova commented on servers/partner-ci/builders/rescan_ds.py
> +        [host.configManager.storageSystem.RescanAllHba() for host in self.hosts]
Make it in a loop. Generators are not suitable in this case

2017-02-01 10:06 UTC, rkhozinov commented on servers/partner-ci/builders/common.prepare.sh
> +[ -z ${VENV_PATH} ] && { export VENV_PATH="${HOME}/${FUEL_RELEASE}-venv"; }
export VENV_PATH=${VENV_PATH:-"~/$FUEL_RELEASE-venv"}

2017-02-01 10:07 UTC, rkhozinov commented on servers/partner-ci/builders/rescan_ds.py
> +
@naumvd95 please remove that

2017-02-01 10:09 UTC, rkhozinov commented on servers/partner-ci/builders/common.prepare.sh
> +
remove empty lines

2017-02-01 10:09 UTC, rkhozinov commented on servers/partner-ci/builders/rescan_ds.py
> +from os import path
add an empty line

2017-02-01 10:10 UTC, rkhozinov commented on servers/partner-ci/builders/rescan_ds.py
> +        [host.configManager.storageSystem.RescanAllHba() for host in self.hosts]
Please link a proof

2017-02-01 10:11 UTC, rkhozinov commented on servers/partner-ci/common.yaml
> +            VENV_PATH=/home/jenkins/90-venv;
try to use $HOME instead

2017-02-01 11:12 UTC, rkhozinov commented on servers/partner-ci/builders/rescan_ds.py
> +            host_view = self.content.viewManager.CreateContainerView(self.datacenter,
flake check has passed with openstack guidelines

2017-02-01 12:17 UTC, naumvd95 approved these changes

2017-02-01 12:17 UTC, rkhozinov reviewed
looks good for me

2017-02-01 13:11 UTC, ekhomyakova approved these changes

2017-02-01 13:11 UTC, ekhomyakova commented on servers/partner-ci/builders/rescan_ds.py
> +from os import path
Seems you don't use it.

2017-02-01 13:11 UTC, ekhomyakova commented on servers/partner-ci/builders/rescan_ds.py
> +    _clusters = []
Seems you don't use it

2017-02-01 13:11 UTC, ekhomyakova approved these changes

2017-02-01 13:11 UTC, merged