ui-testing
rkhozinov/jenkins-jobs pull request #171
Opened 2017-02-13 13:51 UTC by naumvd95

proofs = http://jenkins-tpi.bud.mirantis.net:8080/view/ui/job/10.0.ui.test_bonds/17/console

2017-02-13 14:31 UTC, naumvd95 commented on servers/partner-ci/builders/common.prepare.sh
> +  export SNAPSHOTS_ID="from_iso"
pay attention!!
there are some troubles with it
need to refactor testing-code
**2017-02-13 14:29:55 - INFO environment.py:237 -- Try to find environment '10.0.ui.released''**

2017-02-14 11:01 UTC, rkhozinov requested changes
Separate download job to another pull-request

2017-02-14 11:11 UTC, rkhozinov requested changes

2017-02-14 11:11 UTC, rkhozinov commented on servers/partner-ci/builders/common.prepare.sh
> +if [[ $ISO_FILE == *"Mirantis"* ]] || [[ "${FUEL_RELEASE_VERSION}" == "10" ]] ; then
join conditions

2017-02-14 11:11 UTC, rkhozinov commented on servers/partner-ci/builders/common.prepare.sh
> +  export SNAPSHOTS_ID="from_iso"
**10.0.ui.released** --> **10.0.ui.<iso_number>**

2017-02-14 11:11 UTC, rkhozinov commented on servers/partner-ci/common.yaml
> +      - string:
add to common props

2017-02-14 11:11 UTC, rkhozinov commented on servers/partner-ci/common.yaml
> +          UBUNTU_MIRROR_URL="${MIRROR_HOST:?}/pkgs/snapshots/${UBUNTU_MIRROR_ID:?}/"
add to the common props the next property: 
**MIRROR_HOST=http://mirror.seed-cz1.fuel-infra.org/pkgs/snapshots/**

2017-02-14 11:11 UTC, rkhozinov commented on servers/partner-ci/common.yaml
> +          echo MIRROR_UBUNTU="${UBUNTU_REPOS:?}" >> specific.properties
"MIRROR_UBUNTU=${UBUNTU_REPOS:?}"

2017-02-14 11:11 UTC, rkhozinov commented on servers/partner-ci/common.yaml
> +          echo MIRROR_UBUNTU="${UBUNTU_REPOS:?}" >> specific.properties
java properties: 

MIRROR=asdfadsf

bash properties
MIRROR="asdf"

2017-02-14 11:11 UTC, rkhozinov commented on servers/partner-ci/common.yaml
> +          echo MIRROR_UBUNTU="${UBUNTU_REPOS:?}" >> specific.properties
`echo "MIRROR_UBUNTU=${UBUNTU_REPOS:?}"`

2017-02-14 11:11 UTC, rkhozinov commented on servers/partner-ci/builders/ui.test.sh
> +   -i ${ISO_STORAGE}/${ISO_FILE:?}
`-i ${ISO_STORAGE:?}/${ISO_FILE:?}`

2017-02-14 11:11 UTC, rkhozinov commented on servers/partner-ci/builders/common.prepare.sh
> +[[ -d $VENV_PATH ]] || virtualenv --clear "${VENV_PATH}"
`[[ -d $VENV_PATH ]] `--> `[ -d $VENV_PATH ] `OR `test -d $VENV_PATH`

2017-02-14 13:17 UTC, naumvd95 commented on servers/partner-ci/builders/common.prepare.sh
> +if [[ $ISO_FILE == *"Mirantis"* ]] || [[ "${FUEL_RELEASE_VERSION}" == "10" ]] ; then
there is different conditions
need to refactor this cases
i will make the issue

2017-02-14 13:17 UTC, naumvd95 commented on servers/partner-ci/builders/common.prepare.sh
> +if [[ $ISO_FILE == *"Mirantis"* ]] || [[ "${FUEL_RELEASE_VERSION}" == "10" ]] ; then
https://github.com/rkhozinov/jenkins-jobs/issues/175

2017-02-14 13:17 UTC, naumvd95 commented on servers/partner-ci/builders/common.prepare.sh
> +  export SNAPSHOTS_ID="from_iso"
done

2017-02-14 13:17 UTC, naumvd95 commented on servers/partner-ci/builders/common.prepare.sh
> +[[ -d $VENV_PATH ]] || virtualenv --clear "${VENV_PATH}"
done

2017-02-14 13:17 UTC, naumvd95 commented on servers/partner-ci/builders/ui.test.sh
> +   -i ${ISO_STORAGE}/${ISO_FILE:?}
done

2017-02-14 13:17 UTC, naumvd95 commented on servers/partner-ci/common.yaml
> +      - string:
done

2017-02-14 13:17 UTC, naumvd95 commented on servers/partner-ci/common.yaml
> +          UBUNTU_MIRROR_URL="${MIRROR_HOST:?}/pkgs/snapshots/${UBUNTU_MIRROR_ID:?}/"
done

2017-02-14 13:17 UTC, naumvd95 commented on servers/partner-ci/common.yaml
> +          echo MIRROR_UBUNTU="${UBUNTU_REPOS:?}" >> specific.properties
done

2017-02-14 13:24 UTC, rkhozinov commented on servers/partner-ci/builders/build-job-download-iso.sh
>  aria2c --seed-time 0 "${MAGNET_LINK}" -d "${WORKSPACE}"
why you don't download iso directly to /storage/downloads?

2017-02-14 13:39 UTC, rkhozinov requested changes

2017-02-14 13:39 UTC, rkhozinov commented on servers/partner-ci/builders/common.prepare.sh
> -  *10* ) export REQS_BRANCH="stable/newton" ;;
join with line 30

2017-02-14 13:41 UTC, rkhozinov requested changes

2017-02-14 13:41 UTC, rkhozinov commented on servers/partner-ci/builders/common.prepare.sh
> +if [[ $ISO_FILE == *"Mirantis"* ]] || [[ "${FUEL_RELEASE_VERSION}" == "10" ]] ; then
`FUEL_RELEASE_VERSION` - where do we initialize the var?

2017-02-14 13:47 UTC, rkhozinov requested changes

2017-02-14 13:47 UTC, rkhozinov commented on servers/partner-ci/builders/ui.test.sh
> +  if [[ "${UPDATE_MASTER}" == "true" ]] && [[ ${FUEL_RELEASE} != *"80"* ]] && [[ ${FUEL_RELEASE} != *"100"* ]]; then
try to use switch or regex groups

2017-02-14 13:47 UTC, rkhozinov commented on servers/partner-ci/common.yaml
> +            ISO_STORAGE=/storage/downloads;
ok

2017-02-14 13:47 UTC, rkhozinov commented on servers/partner-ci/common.yaml
> +            VENV_PATH=$HOME/90-venv;
90-venv is used for fuel90
100-venv is used for fuel100

VENV_PATH wasn't a constant

2017-02-14 13:47 UTC, rkhozinov commented on servers/partner-ci/common.yaml
> +          echo "MIRROR_UBUNTU=${UBUNTU_REPOS:?}" >> specific.properties
ok

2017-02-14 13:47 UTC, rkhozinov commented on servers/partner-ci/common.yaml
> +            ISO_STORAGE=/storage/downloads;
ok

2017-02-14 13:47 UTC, rkhozinov commented on servers/partner-ci/common.yaml
> +            MIRROR_HOST=http://mirror.seed-cz1.fuel-infra.org/pkgs/snapshots/;
ok

2017-02-14 13:47 UTC, rkhozinov commented on servers/partner-ci/builders/common.prepare.sh
>  [ -z "${SNAPSHOTS_ID}" ] && { echo SNAPSHOTS_ID is empty; exit 1; }
remove the check `[ -z "${SNAPSHOTS_ID}" ] && { echo SNAPSHOTS_ID is empty; exit 1; }`

2017-02-14 13:47 UTC, rkhozinov commented on servers/partner-ci/builders/common.prepare.sh
>  [ -z $ISO_FILE ] && (echo "ISO_FILE variable is empty"; exit 1)
remove `[ -z $ISO_FILE ] && (echo "ISO_FILE variable is empty"; exit 1)`
and
change 
`if [[ ${ISO_FILE:?} == *"Mirantis"* ]] || [[ "${FUEL_RELEASE_VERSION}" == "10" ]] `

2017-02-14 14:56 UTC, naumvd95 commented on servers/partner-ci/builders/build-job-download-iso.sh
>  aria2c --seed-time 0 "${MAGNET_LINK}" -d "${WORKSPACE}"
we already talk about that
before moving we need to define ISO_FILE=$(ls *.iso)

2017-02-14 14:56 UTC, naumvd95 commented on servers/partner-ci/builders/common.prepare.sh
> +if [[ $ISO_FILE == *"Mirantis"* ]] || [[ "${FUEL_RELEASE_VERSION}" == "10" ]] ; then
common.yaml:            FUEL_RELEASE_VERSION={fuel_release_checker};

2017-02-14 14:56 UTC, naumvd95 commented on servers/partner-ci/builders/common.prepare.sh
>  [ -z $ISO_FILE ] && (echo "ISO_FILE variable is empty"; exit 1)
done

2017-02-14 14:56 UTC, naumvd95 commented on servers/partner-ci/builders/common.prepare.sh
> -  *10* ) export REQS_BRANCH="stable/newton" ;;
done

2017-02-14 14:56 UTC, naumvd95 commented on servers/partner-ci/builders/ui.test.sh
> +  if [[ "${UPDATE_MASTER}" == "true" ]] && [[ ${FUEL_RELEASE} != *"80"* ]] && [[ ${FUEL_RELEASE} != *"100"* ]]; then
done

2017-02-14 14:56 UTC, naumvd95 commented on servers/partner-ci/common.yaml
> +            VENV_PATH=$HOME/90-venv;
this is common variable, seems this is right
in spec-props i'll define VENV_PATH=$HOME/100-venv;

2017-02-15 10:36 UTC, rkhozinov commented on servers/partner-ci/builders/build-job-download-iso.sh
>  aria2c --seed-time 0 "${MAGNET_LINK}" -d "${WORKSPACE}"
aria2c provide information about downloaded files

2017-02-15 16:39 UTC, rkhozinov requested changes

2017-02-15 16:39 UTC, rkhozinov commented on servers/partner-ci/builders/common.prepare.sh
> +    { echo "$VENV_PATH doesn't exist $VENV_PATH will be recreated"; recreate_venv; }
the statement's logic confuses

2017-02-16 09:18 UTC, rkhozinov approved these changes

2017-02-16 11:10 UTC, rkhozinov requested changes

2017-02-16 11:10 UTC, rkhozinov commented on servers/partner-ci/9.0/contrail.yaml
> +      - 40-get-snapshots
join additional updates with get-snapshots

2017-02-16 15:10 UTC, rkhozinov commented on servers/partner-ci/common.yaml
> +                cat << SPECIFIC_PROPERTIES > specific.properties
indent

2017-02-16 15:15 UTC, rkhozinov requested changes

2017-02-16 15:15 UTC, rkhozinov commented on servers/partner-ci/common.yaml
> +                echo "EXTRA_RPM_REPOS=${EXTRA_RPM_REPOS}" >> get-snapshots.properties
optimize multiple ehos with cat

2017-02-17 13:35 UTC, rkhozinov approved these changes

2017-02-17 13:35 UTC, merged