10.0/zabbix: increase ram on nodes
rkhozinov/jenkins-jobs pull request #260
Opened 2017-03-01 15:26 UTC by naumvd95

2017-03-01 15:32 UTC, rkhozinov requested changes

2017-03-01 15:32 UTC, rkhozinov commented on servers/partner-ci/10.0/zabbix.yaml
> +            ADMIN_NODE_MEMORY=4096;
set 8192 for admin_node

2017-03-02 09:32 UTC, naumvd95 commented on servers/partner-ci/10.0/zabbix.yaml
> +            ADMIN_NODE_MEMORY=4096;
at first need to check it  on ci

2017-03-02 14:34 UTC, rkhozinov approved these changes

2017-03-02 14:35 UTC, rkhozinov requested changes
remove memory assignment

2017-03-03 09:12 UTC, naumvd95 commented
seems its not necessary now

2017-03-03 09:12 UTC, closed without merging