10.0/stub: add fuel-plugin-stub for fuel10
rkhozinov/jenkins-jobs pull request #276
Opened 2017-03-07 15:31 UTC by rkhozinov

2017-03-09 07:29 UTC, naumvd95 commented
@rkhozinov  pls add description to this job

2017-03-09 07:30 UTC, naumvd95 requested changes

2017-03-09 07:30 UTC, naumvd95 commented on servers/partner-ci/10.0/stub.yaml
> +    publishers:
where is  **build-plugin-generic.sh**??

2017-03-09 09:06 UTC, rkhozinov commented
where?

2017-03-13 08:10 UTC, naumvd95 approved these changes

2017-03-15 09:38 UTC, merged