/common.prepare: additional checker to avoid some issues
rkhozinov/jenkins-jobs pull request #294
Opened 2017-03-20 10:14 UTC by naumvd95

2017-03-20 10:19 UTC, rkhozinov approved these changes

2017-03-20 10:19 UTC, rkhozinov requested changes
fix the beginning of the commit to common.prepare:

2017-03-20 10:21 UTC, rkhozinov requested changes

2017-03-20 10:21 UTC, rkhozinov commented on servers/partner-ci/builders/common.prepare.sh
> +      domstat=$(virsh domstate $vm)
`domstat-> domstate`

2017-03-20 10:21 UTC, rkhozinov commented on servers/partner-ci/builders/common.prepare.sh
> +      domstat=$(virsh domstate $vm)
`if [[ $domstat != *"shut"* ]] -> if virsh domstate $vm | grep -e '.*shut.*' -q; then...`

2017-03-20 12:04 UTC, rkhozinov requested changes

2017-03-20 12:04 UTC, rkhozinov commented on servers/partner-ci/builders/common.prepare.sh
> +    for vm in $vms; do
`if [ ! -z "${vms}" ]; then ... fi `<--remove
 ` for vm in ${vms:?}; `<-- change to

2017-03-20 12:22 UTC, naumvd95 commented on servers/partner-ci/builders/common.prepare.sh
> +    for vm in $vms; do
done

2017-03-20 14:36 UTC, rkhozinov requested changes

2017-03-20 14:36 UTC, rkhozinov commented on servers/partner-ci/builders/common.prepare.sh
> +	      sudo service libvirt-bin restart
it's seems that the indent is excess

2017-03-20 14:59 UTC, naumvd95 commented on servers/partner-ci/builders/common.prepare.sh
> +	      sudo service libvirt-bin restart
no, this is github bugs

2017-03-21 10:18 UTC, rkhozinov approved these changes

2017-03-21 10:18 UTC, rkhozinov approved these changes

2017-03-21 10:18 UTC, merged