common: properties parsing mechanism is fixed
rkhozinov/jenkins-jobs pull request #48
Opened 2016-12-01 19:06 UTC by rkhozinov

2016-12-01 19:10 UTC, naumvd95 requested changes

2016-12-01 19:10 UTC, naumvd95 commented on servers/partner-ci/common.yaml
> +
space

2016-12-01 19:13 UTC, rkhozinov commented on servers/partner-ci/common.yaml
> +
ok

2016-12-01 19:14 UTC, naumvd95 submitted a review, later dismissed

2016-12-05 09:36 UTC, rkhozinov commented on servers/partner-ci/9.x/nsxv.yaml
> +          scm_wipe_workspace: true
`scm_wipe_workspace` is the global parameter and its default value is **true**
global variables are passed to all jobs as is.
so we don't reassign the same value

2016-12-05 09:36 UTC, rkhozinov commented on servers/partner-ci/9.x/nsxv.yaml
> +          scm_wipe_workspace: true
+ the same for the 135 line

2016-12-05 09:37 UTC, rkhozinov commented on servers/partner-ci/common.yaml
> +          script-only-if-failed: True
It's ok

2016-12-05 09:38 UTC, rkhozinov commented on servers/partner-ci/9.x/nsxv.yaml
> +          scm_wipe_workspace: true
.

2016-12-05 10:14 UTC, rkhozinov reviewed
it's ok for me

2016-12-05 10:15 UTC, naumvd95 approved these changes
awesome

2016-12-05 10:15 UTC, merged