common: fuel_release_version param is added
rkhozinov/jenkins-jobs pull request #52
Opened 2016-12-05 14:29 UTC by rkhozinov

Related to fuel-qa changes
https://github.com/openstack/fuel-qa/commit/96de67b04506d12047f29cad3d883753b49a425c

2016-12-05 14:45 UTC, naumvd95 requested changes

2016-12-05 14:45 UTC, naumvd95 commented on servers/partner-ci/common.yaml
> +          default: '9.0'
seems we need to override that with {fuel-release}?

2016-12-05 15:02 UTC, rkhozinov commented on servers/partner-ci/common.yaml
> +          default: '9.0'
I thought about it. But for that case we should create some sets of plugins jobs for each version of fuel I meant 9.0, 9.1, 9.2

2016-12-05 15:02 UTC, rkhozinov commented on servers/partner-ci/common.yaml
> +          default: '9.0'
Ideally, we could create
9.1 based on the fuel-qa/9.1 branch
9.x base on the fuel-qa/stable/mitaka

2016-12-05 15:05 UTC, naumvd95 commented on servers/partner-ci/common.yaml
> +          default: '9.0'
and 1 more
there is no 9.0 version, as i know, so default value should be 9.1

2016-12-05 15:30 UTC, rkhozinov commented on servers/partner-ci/common.yaml
> +          default: '9.0'
```
 File "/home/jenkins/workspace/9.1.contrail.5.0.custom.dev/plugin_test/fuel-qa/fuelweb_test/tests/base_test_case.py", line 381, in check_fuel_version
    assert_equal(fuel_release, settings.FUEL_RELEASE_VERSION, err_msg)
AssertionError: Fuel version should be `9.2` but it is `9.0`
```

2016-12-05 18:43 UTC, rkhozinov commented
@naumvd95 stable/5.0.0 has been created by @ilush
and now we should create separate set of jobs to check the ref https://review.openstack.org/#/c/407129/

2016-12-06 08:25 UTC, naumvd95 requested changes
need to check that
do u want to create separate jobs?
or remove current?

2016-12-06 13:45 UTC, naumvd95 approved these changes

2016-12-06 14:05 UTC, naumvd95 requested changes

2016-12-06 14:05 UTC, naumvd95 commented on servers/partner-ci/9.0/contrail.yaml
> +            MULTIPLE_NETWORKS_TEMPLATE=;
seems that is useless?

2016-12-06 14:05 UTC, naumvd95 commented on servers/partner-ci/9.0/contrail.yaml
> +    plugin-version: '5.0.0'
did u checked, that is no diffs with test-cases?

2016-12-06 14:05 UTC, naumvd95 commented on servers/partner-ci/9.0/contrail.yaml
> +          testrail_suite: "[9.0][PCE] Fuel plugin contrail v5.0.0 Regression"
maybe we need to create separate regression suite or rename current?

2016-12-06 16:27 UTC, naumvd95 requested changes

2016-12-06 16:27 UTC, naumvd95 commented on servers/partner-ci/common.yaml
> +=======
merge conflict!!!!!

2016-12-06 16:33 UTC, rkhozinov commented on servers/partner-ci/9.0/contrail.yaml
> +            MULTIPLE_NETWORKS_TEMPLATE=;
they are used in tests, let's save it for custom

2016-12-06 16:34 UTC, rkhozinov commented on servers/partner-ci/9.0/contrail.yaml
> +    plugin-version: '5.0.0'
is it used in tests?

2016-12-06 16:34 UTC, rkhozinov commented on servers/partner-ci/9.0/contrail.yaml
> +          testrail_suite: "[9.0][PCE] Fuel plugin contrail v5.0.0 Regression"
we'll rename current

2016-12-08 08:53 UTC, naumvd95 approved these changes

2016-12-08 13:58 UTC, rkhozinov commented on tox.ini
>     jenkins-jobs --conf {env:CONFIG} test {env:SERVERS}/7.0/vcenter.yaml:{env:COMMON}   -o {env:OUTPUT}
Remove old

2016-12-08 13:59 UTC, rkhozinov commented on tox.ini
>     jenkins-jobs --conf {env:CONFIG} test {env:SERVERS}/7.0/vcenter.yaml:{env:COMMON}   -o {env:OUTPUT}
Also need to add pip requirements

2016-12-08 15:55 UTC, rkhozinov commented on tox.ini
>  #deps = -r{toxinidir}/conf/requirements.txt
restore that.
get reqs from the jenkins-jobs-infra

2016-12-09 10:10 UTC, merged